[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NCDACdb"
version = "0.0.1"
authors = [
  { name="Chris Callaghan", email="ccallaghan@csg.org" },
]
description = "A small Python toolkit for working with the North Carolina Department of Adult Correction data."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cllghn/NCDACdb"
"Bug Tracker" = "https://github.com/cllghn/NCDACdb/issues"